# Generated by Django 4.0.5 on 2022-06-26 09:58

import book.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField(verbose_name='Truyện')),
                ('user', models.IntegerField(verbose_name='Người tặng')),
                ('gift_number', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số quà tặng')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Ngày tặng')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField(verbose_name='Truyện')),
                ('user', models.IntegerField(verbose_name='Người đánh giá')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='Ngày thêm')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên truyện')),
                ('image', models.ImageField(blank=True, default='static/img/brand/image_book.png', max_length=255, null=True, upload_to=book.models.image_book_path, verbose_name='Ảnh truyện')),
                ('author', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('url', models.TextField(blank=True, null=True)),
                ('des', models.TextField(blank=True, null=True, verbose_name='Mô tả truyện đầy đủ')),
                ('trang_thai', models.IntegerField(choices=[(0, 'Chưa duyệt'), (1, 'Còn tiếp'), (2, 'Tạm dừng'), (3, 'Đã xong')], default=0, verbose_name='Trạng thái')),
                ('gift', models.FloatField(default=0)),
                ('de_cu', models.BooleanField(default=False, verbose_name='Đề cử')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('chapter', models.FileField(blank=True, max_length=255, null=True, upload_to=book.models.chapter_path, verbose_name='Danh sách chương')),
                ('comment', models.FileField(blank=True, max_length=255, null=True, upload_to=book.models.cmt_path, verbose_name='Bình luận')),
                ('name_bk', models.FileField(blank=True, max_length=255, null=True, upload_to=book.models.name_path, verbose_name='Gói name')),
                ('tag', models.ManyToManyField(blank=True, to='book.tag')),
                ('the_loai', models.ManyToManyField(blank=True, to='book.theloai')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
        ),
    ]
